/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.interfaz;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import jp.auxiliar.ModuloPropiedades;

/**
 *
 * @author Joaquin
 */
public class MostrarCaratula extends javax.swing.JFrame {
    
    private Image imagen;
    private static final int FACTOR = ModuloPropiedades.dimensionCaratula;
    private static double factorX = 1.0;
    private static double factorY = 1.0;

    /**
     * Creates new form MostrarCaratula
     */
    public MostrarCaratula(Image imagen) {
        this.imagen = imagen;
        if(imagen.getHeight(this)>FACTOR){
            factorY = imagen.getHeight(this) /  FACTOR;
        }
        if(imagen.getWidth(this)>FACTOR){
            factorX = imagen.getWidth(this) /  FACTOR;
        }
        initComponents();
        ImagePanel jpanel = (ImagePanel)jPanel1;
        this.setSize((jpanel.anchura()+1),(jpanel.altura()+29));
        System.out.println("Envoltura: "+jpanel.anchura()+":"+ jpanel.altura());
        System.out.println("Envoltura3: "+this.getWidth()+":"+ this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ImagePanel(this.imagen);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caratula");
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private class ImagePanel extends JPanel {
	Image image;
	ImageObserver imageObserver; 
	
	ImagePanel(Image imagen) {
		ImageIcon icon = new ImageIcon(imagen);
		image = icon.getImage();
		imageObserver = icon.getImageObserver();
	}

        @Override
	public void paint( Graphics g ) {
		super.paint( g ) ;
		g.drawImage(image,  0 , 0 , this.anchura(), this.altura(), imageObserver);
                System.out.println("Envoltura2: "+this.anchura()+":"+ this.altura());
	}
        
        public int altura(){
            return (int)(image.getHeight(imageObserver)/factorY);
        }
        public int anchura(){
            return (int)(image.getWidth(imageObserver)/factorX);
        }
    }

}
